Repository ecoacoustics/web-components, pull requests merged in 2024-09, with the labels that each got.

#161 Remove positive only classifications
  dev/use-cases/dani-alternative.html
  dev/use-cases/dani.html
  dev/use-cases/nsw.html
  dev/use-cases/phil.html
  dev/use-cases/slade-classification.html
  dev/use-cases/slade-verification.html
  dev/use-cases/use-case-6.html
  dev/verification-grid.html
  docs-src/examples/verification/classification.md
  docs-src/examples/verification/multi-additional.md
  docs-src/examples/verification/multi.md
  docs-src/examples/verification/single-additional.md
  docs-src/examples/verification/single.md
  docs/useCases.md
  package.json
  pnpm-lock.yaml
  src/components/decision/classification/classification.fixture.ts
  src/components/decision/classification/classification.spec.ts
  src/components/decision/classification/classification.ts
  src/components/decision/classification/css/style.css
  src/components/decision/css/style.css
  src/components/decision/decision.fixture.ts
  src/components/decision/decision.spec.ts
  src/components/decision/decision.ts
  src/components/decision/skip/skip.ts
  src/components/decision/unsure/unsure.ts
  src/components/decision/verification/verification.fixture.ts
  src/components/decision/verification/verification.spec.ts
  src/components/decision/verification/verification.ts
  src/components/media-controls/media-controls.ts
  src/components/verification-grid-settings/verification-grid-settings.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/css/style.css
  src/components/verification-grid/help-dialog.ts
  src/components/verification-grid/verification-grid.ts
  src/helpers/themes/decisionColors.ts
  src/helpers/themes/theming.css
  src/helpers/types/advancedTypes.ts
  src/models/decisions/classification.ts
  src/models/decisions/decision.ts
  src/models/decisions/verification.ts
  src/models/subject.ts
  src/services/colors.ts
  src/tests/helpers.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: Architecture, design, stakeholder-P, stakeholder-S, ui

#173 Add a progress bar to show dataset progress
  src/components/axes/css/style.css
  src/components/data-source/data-source.ts
  src/components/decision/classification/classification.ts
  src/components/decision/css/style.css
  src/components/decision/decision.ts
  src/components/index.ts
  src/components/indicator/css/style.css
  src/components/progress-bar/css/style.css
  src/components/progress-bar/progress-bar.ts
  src/components/progress-bar/progrss-bar.fixture.ts
  src/components/progress-bar/progrss-bar.spec.ts
  src/components/spectrogram/css/style.css
  src/components/verification-grid-tile/css/style.css
  src/components/verification-grid/css/style.css
  src/components/verification-grid/verification-grid.ts
  src/helpers/audio/worker.ts
  src/helpers/themes/theming.css
  src/services/gridPageFetcher.ts
  src/tests/axes-spectrogram/axes-spectrogram.e2e.spec.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
  webcomponents.code-workspace
Labels: enhancement, design, stakeholder-N

#175 Fix: Unplayable after reaching the end of recording
  dev/verification-grid.html
  src/components/indicator/css/style.css
  src/components/indicator/indicator.ts
  src/components/media-controls/media-controls.ts
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/helpers/audio/high-accuracy-time-processor.ts
  src/helpers/audio/messages.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.spec.ts
  src/tests/helpers.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: bug, stakeholder-N, stakeholder-P, stakeholder-S, ui

#177 Compact the verification grid tile chrome
  src/components/indicator/css/style.css
  src/components/media-controls/css/style.css
  src/components/media-controls/media-controls.ts
  src/components/progress-bar/css/style.css
  src/components/verification-grid-tile/css/style.css
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/css/style.css
  src/components/verification-grid/verification-grid.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
Labels: style / refactoring, design, ui

#186 Feat: Grid tiles automatically size to fill grid
  .prettierrc
  dev/spectrogram.html
  dev/use-cases/dani-alternative.html
  dev/use-cases/dani.html
  dev/use-cases/nsw.html
  dev/use-cases/phil.html
  dev/use-cases/slade-classification.html
  dev/use-cases/slade-verification.html
  dev/use-cases/use-case-6.html
  dev/verification-grid.html
  src/components/axes/axes.ts
  src/components/axes/css/style.css
  src/components/indicator/indicator.ts
  src/components/spectrogram/css/style.css
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-settings/verification-grid-settings.fixture.ts
  src/components/verification-grid-settings/verification-grid-settings.ts
  src/components/verification-grid-tile/css/style.css
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/css/style.css
  src/components/verification-grid/verification-grid.ts
  src/helpers/controllers/dynamic-grid-sizes.ts
  src/helpers/themes/theming.css
  src/models/unitConverters.ts
  src/tests/__snapshots__/single-verification-grid-grid-sizes-desktop-should-look-correct-with-slot-content/single-verification-grid-grid-sizes-desktop-should-look-correct-with-slot-content-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-desktop-should-look-correct/single-verification-grid-grid-sizes-desktop-should-look-correct-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-landscape-tablet-should-look-correct-with-slot-content/single-verification-grid-grid-sizes-landscape-tablet-should-look-correct-with-slot-content-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-landscape-tablet-should-look-correct/single-verification-grid-grid-sizes-landscape-tablet-should-look-correct-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-laptop-should-look-correct-with-slot-content/single-verification-grid-grid-sizes-laptop-should-look-correct-with-slot-content-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-laptop-should-look-correct/single-verification-grid-grid-sizes-laptop-should-look-correct-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-mobile-should-look-correct-with-slot-content/single-verification-grid-grid-sizes-mobile-should-look-correct-with-slot-content-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-mobile-should-look-correct/single-verification-grid-grid-sizes-mobile-should-look-correct-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-portrait-tablet-should-look-correct-with-slot-content/single-verification-grid-grid-sizes-portrait-tablet-should-look-correct-with-slot-content-1.png
  src/tests/__snapshots__/single-verification-grid-grid-sizes-portrait-tablet-should-look-correct/single-verification-grid-grid-sizes-portrait-tablet-should-look-correct-1.png
  src/tests/axes-spectrogram/axes-spectrogram.e2e.fixture.ts
  src/tests/axes-spectrogram/axes-spectrogram.e2e.spec.ts
  src/tests/helpers.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: enhancement, Architecture, ui

#197 ci: Enable publish and release workflow
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .release-please-manifest.json
  package.json
  src/components/axes/axes.ts
  tsconfig.json
Labels: CI, Architecture

#199 chore(main): release web-components 1.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
