Repository ecoacoustics/web-components, pull requests merged in 2024-11, with the labels that each got.

#241 docs: Add cane toads verification deployment
  docs-src/deployments/cane-toads.md
  src/components/data-source/data-source.ts
  src/services/gridPageFetcher.ts
  src/services/modelParser.ts
  src/services/subjectParser.ts
Labels: documentation, stakeholder-S

#240 fix: Downloading callback paginated items
  .gitattributes
  dev/theme/theme.ts
  dev/use-cases/ecosounds.html
  dev/use-cases/index.html
  public/test-items-2.csv
  public/test-items-2.json
  public/test-items-2.tsv
  src/components/data-source/data-source.fixture.ts
  src/components/data-source/data-source.spec.ts
  src/components/data-source/data-source.ts
  src/components/decision/verification/verification.spec.ts
  src/components/spectrogram/spectrogram.ts
  src/models/subject.spec.ts
  src/models/subject.ts
  src/tests/helpers.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  vite.config.ts
Labels: bug, triage: high

#244 chore(main): release web-components 1.2.3
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#246 fix: Incorrect verification decision tag updates
  .prettierignore
  dev/cdn.html
  dev/use-cases/dani-alternative.html
  dev/verification-grid-callback.html
  dev/verification-grid.html
  public/test-items.json
  src/components/decision/decision.ts
  src/components/decision/verification/verification.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/models/decisions/decision.ts
  src/models/decisions/verification.spec.ts
  src/models/decisions/verification.ts
  src/models/subject.spec.ts
  src/models/subject.ts
  src/polyfills/userAgentData.ts
  src/services/colors.ts
  src/services/subjectParser.spec.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: bug, triage: high

#247 chore(main): release web-components 1.2.4
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#248 fix: support calling toJSON on downloaded subjects
  dev/use-cases/ecosounds.html
  src/models/subject.spec.ts
  src/models/subject.ts
Labels: enhancement

#249 chore(main): release web-components 1.2.5
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#251 chore(main): release web-components 1.2.6
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#254 chore(main): release web-components 1.3.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
