Repository ecoacoustics/web-components, pull requests merged in 2024-10, with the labels that each got.

#201 Fix: Spectrograms performing double initial render
  dev/spectrogram.html
  src/components/axes/axes.fixture.ts
  src/components/data-source/data-source.fixture.ts
  src/components/decision/classification/classification.fixture.ts
  src/components/decision/verification/verification.fixture.ts
  src/components/indicator/indicator.fixture.ts
  src/components/info-card/info-card.fixture.ts
  src/components/media-controls/media-controls.fixture.ts
  src/components/progress-bar/progrss-bar.fixture.ts
  src/components/spectrogram/single-spectrogram.fixture.ts
  src/components/spectrogram/spectrogram.spec.ts
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-settings/verification-grid-settings.fixture.ts
  src/components/verification-grid-tile/verification-grid-tile.fixture.ts
  src/components/verification-grid/verification-grid.fixture.ts
  src/services/modelParser.spec.ts
  src/services/verificationParser.spec.ts
  src/tests/assertions.ts
  src/tests/axes-spectrogram/axes-spectrogram.e2e.fixture.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
  src/tests/indicator-spectrogram/indicator-spectrogram-media-controls.e2e.fixture.ts
  src/tests/spectrogram-media-controls/spectrogram-media-controls.e2e.fixture.ts
  src/tests/spectrogram-media-controls/spectrogram-media-controls.e2e.spec.ts
  src/tests/test-bed.spec.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  webcomponents.code-workspace
Labels: bug

#209 Feat: Add the ability to transform subject urls
  src/components/data-source/data-source.ts
  src/components/verification-grid/verification-grid.ts
  src/helpers/attributes.ts
  src/services/gridPageFetcher.ts
Labels: enhancement

#210 chore(main): release web-components 1.1.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#207 Docs: Add goshawk verification deployment
  .gitattributes
  .github/workflows/docs-publish.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  docs-src/_includes/layouts/deployment.11ty.js
  docs-src/deployments/goshawk.md
  docs-src/public/README.txt
  docs-src/public/goshawk.csv
  docs/media/concepts.drawio.svg
  docs/media/library.png
  docs/media/listen.png
  docs/media/paging.drawio.svg
  docs/media/search-grid.png
  eleventy.config.js
  public/120hz.wav
  public/diagnostic.wav
  public/ecosounds.csv
  public/example.flac
  public/example.wav
  public/example2.flac
  public/example_34s.flac
  public/kaleidoscope.csv
  public/merged_diagnostic.wav
  public/test-items-2.csv
  public/test-items-2.tsv
  src/components/data-source/data-source.ts
  src/services/dataSourceFetcher.ts
Labels: documentation, stakeholder-P

#211 CI: Allow manual trigger to run website publishing
  .github/workflows/docs-publish.yml
Labels: CI

#203 Fix: theming styles are applied multiple times
  src/components/media-controls/media-controls.fixture.ts
  src/components/progress-bar/progrss-bar.fixture.ts
  src/components/progress-bar/progrss-bar.spec.ts
  src/helpers/themes/globalStyles.css
  src/helpers/themes/theming.css
  src/mixins/abstractComponent.ts
Labels: bug, design

#212 chore(main): release web-components 1.1.3
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#205 Fix: Result downloads for callback paginated sources
  dev/verification-grid-callback.html
  dev/verification-grid.html
  index.html
  src/components/data-source/data-source.ts
  src/services/gridPageFetcher.ts
  src/services/urlSourcedFetcher.ts
Labels: bug

#216 chore(main): release web-components 1.1.4
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#217 Fix: Reduce focus area for keyboard shortcuts
  dev/verification-grid.html
  src/components/decision/classification/classification.fixture.ts
  src/components/decision/decision.ts
  src/components/decision/verification/verification.fixture.ts
  src/components/media-controls/media-controls.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
  webcomponents.code-workspace
Labels: bug, triage: medium

#221 chore(main): release web-components 1.1.5
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#227 feat(build): Emit ESM modules in build output
  dev/cdn.html
  index.html
  package.json
  src/components/decision/decision.ts
  src/components/index.ts
  src/components/info-card/info-card.ts
  src/components/logger/logger.ts
  src/components/media-controls/media-controls.ts
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-settings/verification-grid-settings.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/helpers/constants/contextTokens.ts
  src/helpers/resizeObserver.ts
  src/polyfills/userAgentData.ts
  vite.config.ts
Labels: enhancement, Architecture

#231 chore(main): release web-components 1.2.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#222 Fix: Parsing of tag model arrays on subject model
  package.json
  public/test-items.json
  src/models/subject.ts
  src/services/gridPageFetcher.ts
  src/services/modelParser.ts
  src/services/subjectParser.spec.ts
  src/services/subjectParser.ts
  src/services/verificationParser.spec.ts
  src/services/verificationParser.ts
Labels: bug, triage: high

#232 chore(main): release web-components 1.2.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#233 ci(dependencies): Cache lfs assets in checkout
  .github/workflows/docs-publish.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: enhancement, dependencies, CI, triage: high

#238 chore(main): release web-components 1.2.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
