Repository ecoacoustics/web-components, pull requests merged in 2025-09, with the labels that each got.

#486 chore(main): release web-components 5.3.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#495 fix: Skip decisions not showing in progress meter
  dev/use-cases/nsw.html
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: bug, ui

#498 chore(main): release web-components 5.3.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#522 fix: Removes box shadow for single tile views
  dev/use-cases/shoelace-host-dark.html
  src/components/verification-grid/css/style.css
  src/components/verification-grid/verification-grid.ts
Labels: bug

#524 chore(main): release web-components 5.3.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#525 chore(main): release web-components 5.3.3
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#527 fix: Don't render indicator without unit converter
  src/components/indicator/indicator.spec.ts
  src/components/indicator/indicator.ts
Labels: bug

#529 chore(main): release web-components 6.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
