Repository ecoacoustics/web-components, pull requests merged in 2025-07, with the labels that each got.

#390 fix: Don't show "pointer" cursor on 1x1 grids
  src/components/verification-grid-tile/css/style.css
  src/components/verification-grid-tile/verification-grid-tile.fixture.ts
  src/components/verification-grid-tile/verification-grid-tile.spec.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
Labels: bug

#392 chore(main): release web-components 3.3.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#393 feat: element ref ability inmedia-controls "for"
  src/components/media-controls/media-controls.fixture.ts
  src/components/media-controls/media-controls.spec.ts
  src/components/media-controls/media-controls.ts
Labels: enhancement, triage: high, design, ui

#394 chore(main): release web-components 3.4.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#401 Reduce test flakyness
  package.json
  pnpm-lock.yaml
  src/components/annotate/annotate.fixture.ts
  src/components/annotation/annotation.fixture.ts
  src/components/axes/axes.fixture.ts
  src/components/data-source/data-source.fixture.ts
  src/components/decision/classification/classification.fixture.ts
  src/components/decision/classification/classification.spec.ts
  src/components/decision/verification/verification.fixture.ts
  src/components/decision/verification/verification.spec.ts
  src/components/indicator/indicator.fixture.ts
  src/components/info-card/info-card.fixture.ts
  src/components/media-controls/media-controls.fixture.ts
  src/components/media-controls/media-controls.spec.ts
  src/components/progress-bar/progrss-bar.fixture.ts
  src/components/spectrogram/single-spectrogram.fixture.ts
  src/components/tag/tag.fixture.ts
  src/components/verification-grid-settings/verification-grid-settings.fixture.ts
  src/components/verification-grid-tile/verification-grid-tile.fixture.ts
  src/components/verification-grid/verification-grid.fixture.ts
  src/components/verification-grid/verification-grid.spec.ts
  src/helpers/styles/styles.fixture.ts
  src/helpers/userAgentData/userAgent.fixture.ts
  src/helpers/userAgentData/userAgent.spec.ts
  src/mixins/chrome/chromeHost/chromeHost.fixture.ts
  src/mixins/chrome/chromeProvider/chromeProvider.fixture.ts
  src/tests/assertions.ts
  src/tests/axes-spectrogram/axes-spectrogram.e2e.fixture.ts
  src/tests/axes-spectrogram/axes-spectrogram.e2e.spec.ts
  src/tests/fixtures.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.spec.ts
  src/tests/helpers.ts
  src/tests/indicator-spectrogram/indicator-spectrogram-media-controls.e2e.fixture.ts
  src/tests/spectrogram-media-controls/spectrogram-media-controls.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: CI

#402 chore(main): release web-components 3.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#411 chore(main): release web-components 3.5.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#428 chore(main): release web-components 4.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#434 chore(main): release web-components 4.2.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
