Repository ecoacoustics/web-components, pull requests merged in 2025-02, with the labels that each got.

#287 fix: Space to play with no grid selection should play all
  src/components/media-controls/media-controls.ts
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/verification-grid.ts
  src/helpers/keyboard.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.spec.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  src/tests/verification-grid/verification-grid.e2e.spec.ts
Labels: bug, triage: low, stakeholder-S, ui, stakeholder-SH

#290 feat: Add support for Uppercase.Dot.Casing
  src/services/caseConverters.spec.ts
  src/services/caseConverters.ts
  src/services/modelParser.ts
  src/services/subjectParser.ts
Labels: bug, stakeholder-S

#291 chore(main): release web-components 1.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#296 chore(main): release web-components 2.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#298 fix: Hard lock dependency versions
  .github/workflows/docs-publish.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  dev/source-build.html
  index.html
  package.json
  pnpm-lock.yaml
  src/helpers/audio/audio.ts
  src/helpers/audio/colors.ts
  src/helpers/decorators.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
  src/tests/full-spectrogram/full-spectrogram.e2e.spec.ts
Labels: bug, dependencies, CI, cdn

#300 chore(main): release web-components 2.0.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
