Repository ecoacoustics/web-components, pull requests merged in 2025-01, with the labels that each got.

#267 chore(main): release web-components 1.4.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#273 docs: Add generic verification deployment
  docs-src/deployments/verification.md
Labels: documentation

#275 fix: Incorrect file name for local results
  dev/use-cases/nsw.html
  src/components/data-source/data-source.ts
  src/services/urlSourcedFetcher.ts
Labels: bug, stakeholder-P, stakeholder-SH

#276 chore(main): release web-components 1.4.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
