Repository ecoacoustics/web-components, pull requests merged in 2025-08, with the labels that each got.

#445 chore(main): release web-components 5.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#451 chore(main): release web-components 5.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#452 feat: Add oe-skip button
  dev/use-cases/ecosounds.html
  src/components/decision/skip/skip.ts
  src/components/verification-grid/verification-grid.ts
  src/index.ts
  src/tests/verification-grid/verification-grid.e2e.fixture.ts
  vite.config.ts
Labels: enhancement

#413 fix: Edge case spectrogram attribute parsing
  dev/full-spectrogram.html
  dev/use-cases/shoelace-host.html
  src/components/bootstrap-modal/slides/advanced-shortcuts/advanced-shortcuts.ts
  src/components/bootstrap-modal/slides/shortcuts/shortcuts.ts
  src/components/spectrogram/spectrogram.spec.ts
  src/components/spectrogram/spectrogram.ts
  src/components/verification-grid-tile/verification-grid-tile.ts
  src/components/verification-grid/css/style.css
  src/helpers/numbers.spec.ts
  src/helpers/numbers.ts
  src/helpers/powers.spec.ts
  src/helpers/powers.ts
  src/helpers/types/advancedTypes.ts
Labels: bug

#460 chore(main): release web-components 5.2.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#472 fix: contrast for progress bar's undecided color
  src/components/progress-bar/css/style.css
Labels: bug

#476 chore(main): release web-components 5.2.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
